In [1]:
!pip install duckdb pandas

Collecting duckdb
  Downloading duckdb-1.5.5-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading duckdb-1.5.5-cp314-cp314-win_amd64.whl (13.7 MB)
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
    --------------------------------------- 0.3/13.7 MB ? eta -:--:--
    --------------------------------------- 0.3/13.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/13.7 MB 605.9 kB/s eta 0:00:22
   - -------------------------------------- 0.5/13.7 MB 605.9 kB/s eta 0:00:22
   - -------------------------------------- 0.5/13.7 MB 605.9 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/13.7 MB 523.8 kB/s eta 0:00:25
   --- ------------------------------------ 1.0/13.7 MB 567.1 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/13.7 MB 567.1 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/13.7 MB 567.1 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/13.7 MB 567.1 kB/s eta 0:00:23
   --- ------------------------------------ 1.3/13.7 MB 511.3 kB/s eta 0:00:25
   ---- ----------------------------------- 1.6/13.7 MB 542.5 kB/s eta 0:00:23
   ---- ----------------------------------- 1.6/13.7 MB 542.5 kB/s eta 0:00:23
   ---- ----------------------------------- 1.6/13.7 MB 542.5 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/13.7 MB 522.4 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/13.7 MB 522.4 kB/s eta 0:00:23
   ------ --------------------------------- 2.1/13.7 MB 546.4 kB/s eta 0:00:22
   ------ --------------------------------- 2.4/13.7 MB 579.9 kB/s eta 0:00:20
   ------- -------------------------------- 2.6/13.7 MB 610.8 kB/s eta 0:00:19
   ------- -------------------------------- 2.6/13.7 MB 610.8 kB/s eta 0:00:19
   -------- ------------------------------- 2.9/13.7 MB 636.0 kB/s eta 0:00:17
   --------- ------------------------------ 3.1/13.7 MB 665.1 kB/s eta 0:00:16
   --------- ------------------------------ 3.4/13.7 MB 693.6 kB/s eta 0:00:15
   ---------- ----------------------------- 3.7/13.7 MB 721.4 kB/s eta 0:00:14
   ------------ --------------------------- 4.2/13.7 MB 769.6 kB/s eta 0:00:13
   ------------- -------------------------- 4.5/13.7 MB 791.8 kB/s eta 0:00:12
   ------------- -------------------------- 4.5/13.7 MB 791.8 kB/s eta 0:00:12
   ------------- -------------------------- 4.7/13.7 MB 784.7 kB/s eta 0:00:12
   -------------- ------------------------- 5.0/13.7 MB 807.7 kB/s eta 0:00:11
   --------------- ------------------------ 5.2/13.7 MB 830.4 kB/s eta 0:00:11
   ---------------- ----------------------- 5.8/13.7 MB 871.8 kB/s eta 0:00:10
   ----------------- ---------------------- 6.0/13.7 MB 887.3 kB/s eta 0:00:09
   ------------------- -------------------- 6.6/13.7 MB 930.8 kB/s eta 0:00:08
   ------------------- -------------------- 6.8/13.7 MB 944.1 kB/s eta 0:00:08
   -------------------- ------------------- 7.1/13.7 MB 960.4 kB/s eta 0:00:07
   --------------------- ------------------ 7.3/13.7 MB 958.1 kB/s eta 0:00:07
   ---------------------- ----------------- 7.6/13.7 MB 983.9 kB/s eta 0:00:07
   ----------------------- ---------------- 8.1/13.7 MB 1.0 MB/s eta 0:00:06
   ------------------------ --------------- 8.4/13.7 MB 1.0 MB/s eta 0:00:06
   -------------------------- ------------- 8.9/13.7 MB 1.1 MB/s eta 0:00:05
   --------------------------- ------------ 9.4/13.7 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 10.0/13.7 MB 1.1 MB/s eta 0:00:04
   ------------------------------ --------- 10.5/13.7 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 11.3/13.7 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 11.8/13.7 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 12.1/13.7 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 12.1/13.7 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 12.1/13.7 MB 1.3 MB/s eta 0:00:02
   ------------------------------------ --- 12.6/13.7 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 13.1/13.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.4/13.7 MB 934.2 kB/s eta 0:00:01
   ---------------------------------------  13.6/13.7 MB 791.2 kB/s eta 0:00:01
   ---------------------------------------  13.6/13.7 MB 791.2 kB/s eta 0:00:01
   ---------------------------------------  13.6/13.7 MB 791.2 kB/s eta 0:00:01
   ---------------------------------------  13.6/13.7 MB 791.2 kB/s eta 0:00:01
   ---------------------------------------- 13.7/13.7 MB 755.9 kB/s  0:00:18
Installing collected packages: duckdb
Successfully installed duckdb-1.5.5

In [3]:
import duckdb
file_path = r"C:\Users\User\Documents\nigerian_retail_transactions_full.parquet"
duckdb.query(f"SELECT * FROM '{file_path}' LIMIT 5").df()

,transaction_id,account_id,customer_id,timestamp,amount_ngn,balance_before_ngn,balance_after_ngn,transaction_type,channel,merchant_category_code,merchant_name,location_lga,location_state,device_id,status,fraud_flag
0,42ae7cb0-052b-4c28-a149-8d7d2cc558a1,ACC-00000334,CUS-00000334,2024-09-14 14:59:00,2100.0,248561.187746,246461.187746,debit,web,4814,Airtel,Lagos LGA,Lagos,DEV-5b4184adc38945c2,failed,False
1,ce38456c-5bbb-4a83-992a-09e8fd59b49a,ACC-00004849,CUS-00004849,2024-12-26 01:54:00,73400.0,224711.795501,151311.795501,debit,web,5411,Grand Square,Benue LGA,Benue,DEV-b2b4b029db434254,success,False
2,9e69c19c-93c8-48fc-b2b8-e89d83b40936,ACC-00082189,CUS-00082189,2024-06-15 13:08:00,22600.0,114278.718868,136878.718868,credit,pos,7523,MegaPlaza Parking,Borno LGA,Borno,,success,False
3,eb707378-ac9a-4dd6-9a04-9cfe06970123,ACC-00010867,CUS-00010867,2023-11-18 18:45:00,45900.0,272525.157062,226625.157062,debit,mobile,,,Lagos LGA,Lagos,DEV-5f6ebeaeae504cdd,success,False
4,b29c3f2e-9712-4d9f-ab0e-32dc91493f3e,ACC-00004080,CUS-00004080,2024-04-21 22:48:00,80000.0,169907.403695,89907.403695,debit,branch,,,Lagos LGA,Lagos,,failed,False

In [4]:
row_count = duckdb.query(f"SELECT COUNT(*) FROM '{file_path}'").fetchone()[0]
print(f"Total Rows:{row_count:,}")
duckdb.query(f"DESCRIBE SELECT * FROM '{file_path}'").df()

Total Rows:5,000,000

               column_name   column_type null   key default extra
0           transaction_id       VARCHAR  YES  None    None  None
1               account_id       VARCHAR  YES  None    None  None
2              customer_id       VARCHAR  YES  None    None  None
3                timestamp  TIMESTAMP_NS  YES  None    None  None
4               amount_ngn        DOUBLE  YES  None    None  None
5       balance_before_ngn        DOUBLE  YES  None    None  None
6        balance_after_ngn        DOUBLE  YES  None    None  None
7         transaction_type       VARCHAR  YES  None    None  None
8                  channel       VARCHAR  YES  None    None  None
9   merchant_category_code       VARCHAR  YES  None    None  None
10           merchant_name       VARCHAR  YES  None    None  None
11            location_lga       VARCHAR  YES  None    None  None
12          location_state       VARCHAR  YES  None    None  None
13               device_id       VARCHAR  YES  None    None  None
14                  status       VARCHAR  YES  None    None  None
15              fraud_flag       BOOLEAN  YES  None    None  None

In [8]:
duckdb.query(f"""
SELECT transaction_id, COUNT(*) AS occurances
FROM '{file_path}'
GROUP BY transaction_id
HAVING COUNT(*) > 1
""").df()

Empty DataFrame
Columns: [transaction_id, occurances]
Index: []

In [10]:
duckdb.query(f"""
SELECT channel, COUNT(*) AS total_count
FROM '{file_path}'
GROUP BY channel
ORDER BY total_count DESC
""").df()

  channel  total_count
0  mobile      1749043
1     pos      1501370
2     atm       999469
3     web       500493
4  branch       149372
5    ussd        75336
6   agent        24917

In [11]:
duckdb.query(f"""
SELECT transaction_type, COUNT(*) AS total_count
FROM '{file_path}'
GROUP BY transaction_type
ORDER BY total_count DESC
""").df()

  transaction_type  total_count
0            debit      3250541
1           credit      1749459

In [12]:
duckdb.query(f"""
SELECT location_lga, COUNT(*) AS total_count
FROM '{file_path}'
GROUP BY location_lga
ORDER BY total_count DESC
""").df()

       location_lga  total_count
0         Lagos LGA      1225836
1   Abuja (FCT) LGA       542759
2        Rivers LGA       446381
3          Kano LGA       288046
4       Anambra LGA       239518
5           Oyo LGA       238988
6           Imo LGA       186312
7        Kaduna LGA       159387
8         Delta LGA       135097
9           Edo LGA       125496
10         Ogun LGA       125378
11       Jigawa LGA       110804
12      Katsina LGA       101373
13    Akwa Ibom LGA        97544
14        Benue LGA        89068
15        Kwara LGA        87088
16         Osun LGA        84734
17        Enugu LGA        82221
18         Abia LGA        82067
19      Plateau LGA        73854
20       Sokoto LGA        51632
21        Borno LGA        46956
22  Cross River LGA        45599
23        Ekiti LGA        42847
24       Bauchi LGA        42255
25        Niger LGA        41469
26      Adamawa LGA        39644
27         Ondo LGA        36262
28      Zamfara LGA        25685
29       Taraba LGA        25102
30         Kogi LGA        17579
31         Yobe LGA        15820
32        Gombe LGA        11756
33     Nasarawa LGA        11413
34       Ebonyi LGA         9193
35        Kebbi LGA         8490
36      Bayelsa LGA         6347

In [15]:
duckdb.query(f"""
SELECT
    COUNT(*) - COUNT(transaction_id) AS null_transaction_ids,
    COUNT(*) - COUNT(account_id) AS null_account_ids,
    COUNT(*) - COUNT(customer_id) AS null_customer_ids,
    COUNT(*) - COUNT(timestamp) AS null_timestamps,
    COUNT(*) - COUNT(amount_ngn) AS null_amounts,
    COUNT(*) - COUNT(transaction_type) AS null_transaction_types,
    COUNT(*) - COUNT(channel) AS null_channels,
    COUNT(*) - COUNT(merchant_category_code) AS null_mccs,
    COUNT(*) - COUNT(merchant_name) AS null_merchants,
    COUNT(*) - COUNT(location_lga) AS null_locations
FROM '{file_path}'
""").df()

,null_transaction_ids,null_account_ids,null_customer_ids,null_timestamps,null_amounts,null_transaction_types,null_channels,null_mccs,null_merchants,null_locations
0,0,0,0,0,0,0,0,0,0,0

In [17]:
duckdb.query(f"""
SELECT
    TRIM(transaction_id) AS transaction_id,
    TRIM(account_id) AS account_id,
    TRIM(customer_id) AS customer_id,
    timestamp,
    amount_ngn,
    balance_before_ngn,
    balance_after_ngn,
    TRIM(transaction_type) AS transaction_type,
    TRIM(channel) AS channel,
    TRIM(merchant_category_code) AS merchant_category_code,
    TRIM(merchant_name) AS merchant_name,
    TRIM(location_lga) AS location_lga
FROM '{file_path}'
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,transaction_id,account_id,customer_id,timestamp,amount_ngn,balance_before_ngn,balance_after_ngn,transaction_type,channel,merchant_category_code,merchant_name,location_lga
0,42ae7cb0-052b-4c28-a149-8d7d2cc558a1,ACC-00000334,CUS-00000334,2024-09-14 14:59:00,2100.0,248561.187746,246461.187746,debit,web,4814,Airtel,Lagos LGA
1,ce38456c-5bbb-4a83-992a-09e8fd59b49a,ACC-00004849,CUS-00004849,2024-12-26 01:54:00,73400.0,224711.795501,151311.795501,debit,web,5411,Grand Square,Benue LGA
2,9e69c19c-93c8-48fc-b2b8-e89d83b40936,ACC-00082189,CUS-00082189,2024-06-15 13:08:00,22600.0,114278.718868,136878.718868,credit,pos,7523,MegaPlaza Parking,Borno LGA
3,eb707378-ac9a-4dd6-9a04-9cfe06970123,ACC-00010867,CUS-00010867,2023-11-18 18:45:00,45900.0,272525.157062,226625.157062,debit,mobile,,,Lagos LGA
4,b29c3f2e-9712-4d9f-ab0e-32dc91493f3e,ACC-00004080,CUS-00004080,2024-04-21 22:48:00,80000.0,169907.403695,89907.403695,debit,branch,,,Lagos LGA
...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,c6f96081-96b2-4e90-822d-a24387f52d66,ACC-00001355,CUS-00001355,2023-12-02 20:59:00,45400.0,77658.204727,32258.204727,debit,mobile,,,Kano LGA
4999996,b25a9314-7825-4e07-adbf-afdc2ee6ca7c,ACC-00004405,CUS-00004405,2023-11-17 04:51:00,2200.0,84294.700157,82094.700157,debit,mobile,,,Gombe LGA
4999997,0f3b6f23-b490-479f-ad0f-b7b03d4a7cc0,ACC-00001626,CUS-00001626,2024-09-07 08:41:00,42100.0,312156.538456,270056.538456,debit,pos,4899,DSTV,Ogun LGA
4999998,922a73e0-ba3c-4d62-ba64-d9b7bc2d1378,ACC-00001335,CUS-00001335,2023-12-31 12:51:00,11100.0,171631.383138,160531.383138,debit,pos,4900,PHEDC,Kogi LGA
4999999,2566d477-a923-4377-85a7-741f3433c691,ACC-00007367,CUS-00007367,2023-09-04 06:39:00,7000.0,459358.083123,452358.083123,debit,web,5411,Shoprite,Kano LGA

In [19]:
duckdb.query(f"""
SELECT
   transaction_id,
   account_id,
   customer_id,
   timestamp,
   ROUND(amount_ngn, 0) AS amount_ngn,
   ROUND(balance_before_ngn, 0) AS balance_before_ngn,
   ROUND(balance_after_ngn, 0) AS balance_after_ngn,
   transaction_type,
   channel,
   merchant_category_code,
   merchant_name,
   location_lga
FROM '{file_path}'
""").df()

,transaction_id,account_id,customer_id,timestamp,amount_ngn,balance_before_ngn,balance_after_ngn,transaction_type,channel,merchant_category_code,merchant_name,location_lga
0,42ae7cb0-052b-4c28-a149-8d7d2cc558a1,ACC-00000334,CUS-00000334,2024-09-14 14:59:00,2100.0,248561.0,246461.0,debit,web,4814,Airtel,Lagos LGA
1,ce38456c-5bbb-4a83-992a-09e8fd59b49a,ACC-00004849,CUS-00004849,2024-12-26 01:54:00,73400.0,224712.0,151312.0,debit,web,5411,Grand Square,Benue LGA
2,9e69c19c-93c8-48fc-b2b8-e89d83b40936,ACC-00082189,CUS-00082189,2024-06-15 13:08:00,22600.0,114279.0,136879.0,credit,pos,7523,MegaPlaza Parking,Borno LGA
3,eb707378-ac9a-4dd6-9a04-9cfe06970123,ACC-00010867,CUS-00010867,2023-11-18 18:45:00,45900.0,272525.0,226625.0,debit,mobile,,,Lagos LGA
4,b29c3f2e-9712-4d9f-ab0e-32dc91493f3e,ACC-00004080,CUS-00004080,2024-04-21 22:48:00,80000.0,169907.0,89907.0,debit,branch,,,Lagos LGA
...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,c6f96081-96b2-4e90-822d-a24387f52d66,ACC-00001355,CUS-00001355,2023-12-02 20:59:00,45400.0,77658.0,32258.0,debit,mobile,,,Kano LGA
4999996,b25a9314-7825-4e07-adbf-afdc2ee6ca7c,ACC-00004405,CUS-00004405,2023-11-17 04:51:00,2200.0,84295.0,82095.0,debit,mobile,,,Gombe LGA
4999997,0f3b6f23-b490-479f-ad0f-b7b03d4a7cc0,ACC-00001626,CUS-00001626,2024-09-07 08:41:00,42100.0,312157.0,270057.0,debit,pos,4899,DSTV,Ogun LGA
4999998,922a73e0-ba3c-4d62-ba64-d9b7bc2d1378,ACC-00001335,CUS-00001335,2023-12-31 12:51:00,11100.0,171631.0,160531.0,debit,pos,4900,PHEDC,Kogi LGA
4999999,2566d477-a923-4377-85a7-741f3433c691,ACC-00007367,CUS-00007367,2023-09-04 06:39:00,7000.0,459358.0,452358.0,debit,web,5411,Shoprite,Kano LGA

In [22]:
duckdb.query(f"""
SELECT
    transaction_id,
    account_id,
    customer_id,
    timestamp,
    CAST(amount_ngn AS BIGINT) AS amount_ngn,
    CAST(balance_before_ngn AS BIGINT) AS balance_before_ngn,
    CAST(balance_after_ngn AS BIGINT) AS balance_after_ngn,
    transaction_type,
    channel,
    merchant_category_code,
    merchant_name,
    location_lga
FROM '{file_path}'
""").df()

,transaction_id,account_id,customer_id,timestamp,amount_ngn,balance_before_ngn,balance_after_ngn,transaction_type,channel,merchant_category_code,merchant_name,location_lga
0,42ae7cb0-052b-4c28-a149-8d7d2cc558a1,ACC-00000334,CUS-00000334,2024-09-14 14:59:00,2100,248561,246461,debit,web,4814,Airtel,Lagos LGA
1,ce38456c-5bbb-4a83-992a-09e8fd59b49a,ACC-00004849,CUS-00004849,2024-12-26 01:54:00,73400,224712,151312,debit,web,5411,Grand Square,Benue LGA
2,9e69c19c-93c8-48fc-b2b8-e89d83b40936,ACC-00082189,CUS-00082189,2024-06-15 13:08:00,22600,114279,136879,credit,pos,7523,MegaPlaza Parking,Borno LGA
3,eb707378-ac9a-4dd6-9a04-9cfe06970123,ACC-00010867,CUS-00010867,2023-11-18 18:45:00,45900,272525,226625,debit,mobile,,,Lagos LGA
4,b29c3f2e-9712-4d9f-ab0e-32dc91493f3e,ACC-00004080,CUS-00004080,2024-04-21 22:48:00,80000,169907,89907,debit,branch,,,Lagos LGA
...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,c6f96081-96b2-4e90-822d-a24387f52d66,ACC-00001355,CUS-00001355,2023-12-02 20:59:00,45400,77658,32258,debit,mobile,,,Kano LGA
4999996,b25a9314-7825-4e07-adbf-afdc2ee6ca7c,ACC-00004405,CUS-00004405,2023-11-17 04:51:00,2200,84295,82095,debit,mobile,,,Gombe LGA
4999997,0f3b6f23-b490-479f-ad0f-b7b03d4a7cc0,ACC-00001626,CUS-00001626,2024-09-07 08:41:00,42100,312157,270057,debit,pos,4899,DSTV,Ogun LGA
4999998,922a73e0-ba3c-4d62-ba64-d9b7bc2d1378,ACC-00001335,CUS-00001335,2023-12-31 12:51:00,11100,171631,160531,debit,pos,4900,PHEDC,Kogi LGA
4999999,2566d477-a923-4377-85a7-741f3433c691,ACC-00007367,CUS-00007367,2023-09-04 06:39:00,7000,459358,452358,debit,web,5411,Shoprite,Kano LGA

In [26]:
duckdb.query(f"""
SELECT * REPLACE (
    CAST(amount_ngn AS BIGINT) AS amount_ngn,
    CAST(balance_before_ngn AS BIGINT) AS balance_before_ngn,
    CAST(balance_after_ngn AS BIGINT) AS balance_after_ngn,
    COALESCE(NULLIF(TRIM(merchant_category_code), ''),'N/A') AS merchant_category_code,
    COALESCE(NULLIF(TRIM(merchant_name), ''),  'Non-Merchant') AS merchant_name
)
FROM '{file_path}'
""").df()

,transaction_id,account_id,customer_id,timestamp,amount_ngn,balance_before_ngn,balance_after_ngn,transaction_type,channel,merchant_category_code,merchant_name,location_lga,location_state,device_id,status,fraud_flag
0,42ae7cb0-052b-4c28-a149-8d7d2cc558a1,ACC-00000334,CUS-00000334,2024-09-14 14:59:00,2100,248561,246461,debit,web,4814,Airtel,Lagos LGA,Lagos,DEV-5b4184adc38945c2,failed,False
1,ce38456c-5bbb-4a83-992a-09e8fd59b49a,ACC-00004849,CUS-00004849,2024-12-26 01:54:00,73400,224712,151312,debit,web,5411,Grand Square,Benue LGA,Benue,DEV-b2b4b029db434254,success,False
2,9e69c19c-93c8-48fc-b2b8-e89d83b40936,ACC-00082189,CUS-00082189,2024-06-15 13:08:00,22600,114279,136879,credit,pos,7523,MegaPlaza Parking,Borno LGA,Borno,,success,False
3,eb707378-ac9a-4dd6-9a04-9cfe06970123,ACC-00010867,CUS-00010867,2023-11-18 18:45:00,45900,272525,226625,debit,mobile,N/A,Non-Merchant,Lagos LGA,Lagos,DEV-5f6ebeaeae504cdd,success,False
4,b29c3f2e-9712-4d9f-ab0e-32dc91493f3e,ACC-00004080,CUS-00004080,2024-04-21 22:48:00,80000,169907,89907,debit,branch,N/A,Non-Merchant,Lagos LGA,Lagos,,failed,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,c6f96081-96b2-4e90-822d-a24387f52d66,ACC-00001355,CUS-00001355,2023-12-02 20:59:00,45400,77658,32258,debit,mobile,N/A,Non-Merchant,Kano LGA,Kano,DEV-85c6b1ad42294bf4,success,False
4999996,b25a9314-7825-4e07-adbf-afdc2ee6ca7c,ACC-00004405,CUS-00004405,2023-11-17 04:51:00,2200,84295,82095,debit,mobile,N/A,Non-Merchant,Gombe LGA,Gombe,DEV-5c4f247f6ed6490d,success,False
4999997,0f3b6f23-b490-479f-ad0f-b7b03d4a7cc0,ACC-00001626,CUS-00001626,2024-09-07 08:41:00,42100,312157,270057,debit,pos,4899,DSTV,Ogun LGA,Ogun,,success,False
4999998,922a73e0-ba3c-4d62-ba64-d9b7bc2d1378,ACC-00001335,CUS-00001335,2023-12-31 12:51:00,11100,171631,160531,debit,pos,4900,PHEDC,Kogi LGA,Kogi,,success,False
4999999,2566d477-a923-4377-85a7-741f3433c691,ACC-00007367,CUS-00007367,2023-09-04 06:39:00,7000,459358,452358,debit,web,5411,Shoprite,Kano LGA,Kano,DEV-9fa8a3f8a02b434c,success,False

In [15]:
import os
import duckdb

documents_dir = os.path.expanduser(r"~\Documents")
file_path = os.path.join(
    documents_dir, "nigerian_retail_transactions_full.parquet"
)
duckdb.query(
    f"""
    COPY (
      SELECT * REPLACE (
          CAST(amount_ngn AS BIGINT) AS amount_ngn,
          CAST(balance_before_ngn AS BIGINT) AS balance_before_ngn,
          CAST(balance_after_ngn AS BIGINT) AS balance_after_ngn,
          COALESCE(NULLIF(TRIM(merchant_category_code), ''), 'N/A') AS merchant_category_code,
          COALESCE(NULLIF(TRIM(merchant_name), ''), 'Non_merchant') AS merchant_name
        )
        FROM '{file_path}'
    ) TO 'cleaned_retail_transactions.csv' (HEADER, DELIMITER ',');
"""
)
print("Export complete! 'cleaned_retail_transaction.csv' is saved already for Tableau."
     )

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Export complete! 'cleaned_retail_transaction.csv' is saved already for Tableau.

In [16]:
import os
print(os.path.abspath("cleaned_retail_transactions.csv"))

C:\Users\User\cleaned_retail_transactions.csv

In [1]:
import os
print(os.getcwd())

C:\Users\User